name: Feature branch
on:
  push:
    branches-ignore:
      master

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: |
          node common/scripts/install-run-rush.js install
          node common/scripts/install-run-rush.js build
      - name: Build and test
        run: |
          # todo: iterate over services and packages dir
          cd services/monolith

          npm run build

          npm run test:coverage
